#pragma checksum "..\..\..\UserControls\ucAfterClean.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "9EB4B96F95D99DD816D27D983858F6A74C128736A6661B2A4BF6C2729F248252"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.CustomControl;
using DuplicatePhotosFixer.UserControls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.UserControls {
    
    
    /// <summary>
    /// ucAfterClean
    /// </summary>
    public partial class ucAfterClean : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image chk_mark;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_heading;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_info;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl1;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock duplicatephotoFound;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl2;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock duplicatephotoDeleted;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl3;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock duplicatephotoRetained;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOK;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\UserControls\ucAfterClean.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DuplicatePhotosFixer.CustomControl.ImageButton linklblSettings;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/usercontrols/ucafterclean.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UserControls\ucAfterClean.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.chk_mark = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.lbl_heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.lbl_info = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.lbl1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.duplicatephotoFound = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.lbl2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.duplicatephotoDeleted = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.lbl3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.duplicatephotoRetained = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.btnOK = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.linklblSettings = ((DuplicatePhotosFixer.CustomControl.ImageButton)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

