#pragma checksum "..\..\..\Nags\nagVistaUpgradeNow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D111E48D1557D5751455C20F8C70CF13E942F8FA54222CA7FA7960DC4F39C8E7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagVistaUpgradeNow
    /// </summary>
    public partial class nagVistaUpgradeNow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 21 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_popup;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock heading;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock rtb_TopText;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_block;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick1;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt1;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick2;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt2;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick3;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt3;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick4;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt4;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpgrade;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_mb;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt5;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt6;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnContinueUn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagvistaupgradenow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagVistaUpgradeNow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.img_popup = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.rtb_TopText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.txt_block = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.img_tick1 = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.txt1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.img_tick2 = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.txt2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.img_tick3 = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.txt3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.img_tick4 = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.txt4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.btnUpgrade = ((System.Windows.Controls.Button)(target));
            return;
            case 14:
            this.img_mb = ((System.Windows.Controls.Image)(target));
            return;
            case 15:
            this.txt5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.txt6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.btnContinueUn = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

