#pragma checksum "..\..\..\Nags\frmTrayNagGrabOffer.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "9A8FA0A52DFFC4078F43E945D4B9D8750CFAB60C11E93788B4666B686C0E68FC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// frmTrayNagGrabOffer
    /// </summary>
    public partial class frmTrayNagGrabOffer : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Close;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image close_btn;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image discount_img;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_preview;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_counts;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_saveSpace;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_activateNow;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_claimOffer;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/frmtraynaggraboffer.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\frmTrayNagGrabOffer.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_Close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.close_btn = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.discount_img = ((System.Windows.Controls.Image)(target));
            return;
            case 4:
            this.pb_preview = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.btn_counts = ((System.Windows.Controls.Button)(target));
            return;
            case 6:
            this.lbl_saveSpace = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.lbl_activateNow = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.btn_claimOffer = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

