#pragma checksum "..\..\..\Nags\nagNewTheamEmail1.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "20A0C838E3F892D30294ED1C53E99F9A42D3721D0EB75A62BD21CDD1798E1834"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagNewTheamEmail1
    /// </summary>
    public partial class nagNewTheamEmail1 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_close;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label1;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDupPhotos;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label2;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblSpace;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_block;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick1;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt1;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick2;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt2;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick3;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt3;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick4;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt4;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGetFullVer;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt0;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpgrade;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock key;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink llAlreadyKey;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_mb;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt5;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt6;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\Nags\nagNewTheamEmail1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnContinueUn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagnewtheamemail1.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagNewTheamEmail1.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.img = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.label = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.label1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.lblDupPhotos = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.label2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.lblSpace = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.txt_block = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.img_tick1 = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.txt1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.img_tick2 = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.txt2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.img_tick3 = ((System.Windows.Controls.Image)(target));
            return;
            case 14:
            this.txt3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.img_tick4 = ((System.Windows.Controls.Image)(target));
            return;
            case 16:
            this.txt4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.btnGetFullVer = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.txt = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.txt0 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.btnUpgrade = ((System.Windows.Controls.Button)(target));
            return;
            case 21:
            this.key = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.llAlreadyKey = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 23:
            this.img_mb = ((System.Windows.Controls.Image)(target));
            return;
            case 24:
            this.txt5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.txt6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            this.btnContinueUn = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

