#pragma checksum "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "C848A6462EBABAB84D4DC53C6E215229DB829C9AE73782927721DEEC276CBBE1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Views.Cloud;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Views.Cloud {
    
    
    /// <summary>
    /// frmAmazonLogin
    /// </summary>
    public partial class frmAmazonLogin : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_heading;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label txtSignin;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label1;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtPoint1;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label2;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtPoint2;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label3;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtPoint3;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbcktname;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtacesskey;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtsecretidkey;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnContinue;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/views/cloud/frmamazonlogin.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\Cloud\frmAmazonLogin.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.lbl_heading = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.txtSignin = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.label1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.txtPoint1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.label2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.txtPoint2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.label3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.txtPoint3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.txtbcktname = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.txtacesskey = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.txtsecretidkey = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            return;
            case 13:
            this.btnContinue = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

