#pragma checksum "..\..\..\Views\frmAccountConfirm.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5427B704D4E1EBB9305D3AE45DE1DDCF4FD795442A87494C6C37BD363A6FD216"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Views {
    
    
    /// <summary>
    /// frmAccountConfirm
    /// </summary>
    public partial class frmAccountConfirm : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 47 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_Alert;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock clblPlsWait;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ctxtblock;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ctxtblock1;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_noThanks;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_claimOffer;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_down_arrow;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_thanks;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_expectation;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton reason1;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton reason2;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton reason3;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton reason4;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton reason5;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton reason_other;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock pnl_message;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_message;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock pnl_name;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_name;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock pnl_email;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_email;
        
        #line default
        #line hidden
        
        
        #line 250 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_submit;
        
        #line default
        #line hidden
        
        
        #line 259 "..\..\..\Views\frmAccountConfirm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_skipClose;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/views/frmaccountconfirm.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\frmAccountConfirm.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.img_Alert = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.clblPlsWait = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.ctxtblock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.ctxtblock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.lbl_noThanks = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.btn_claimOffer = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.img_down_arrow = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.lbl_thanks = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.lbl_expectation = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.reason1 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 11:
            this.reason2 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 12:
            this.reason3 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 13:
            this.reason4 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 14:
            this.reason5 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 15:
            this.reason_other = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 16:
            this.pnl_message = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.txt_message = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.pnl_name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.txt_name = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.pnl_email = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.txt_email = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.btn_submit = ((System.Windows.Controls.Button)(target));
            return;
            case 23:
            this.lbl_skipClose = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

