#pragma checksum "..\..\..\Nags\nagUpdateOffer_VPN.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "94C2391C0D4E3D3479C641955A59ECC5651F33B4E579816C8C1A84A73401CA8A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagUpdateOffer_VPN
    /// </summary>
    public partial class nagUpdateOffer_VPN : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pb_Close;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_Icon;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label_heading;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label1;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label2;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_leftImage;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Install;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_clock;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFooter1;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFooter2;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink lblEula;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink lblPP;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagupdateoffer_vpn.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagUpdateOffer_VPN.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pb_Close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.pb_Icon = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.label_heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.label1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.label2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.pb_leftImage = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.lblDes = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.btn_Install = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.pb_clock = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.txt = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.lblFooter1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.lblFooter2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.lblEula = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 14:
            this.lblPP = ((System.Windows.Documents.Hyperlink)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

