#pragma checksum "..\..\..\Nags\nagUpdateOfferAPM.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3B90D3891B7897DF35AE70B8655BAF81CFA394B57E78D1FCC4F5085C659F5C12"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagUpdateOfferAPM
    /// </summary>
    public partial class nagUpdateOfferAPM : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pb_Close;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_Icon;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label_heading;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label1;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image picGraphic;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image tsr_logo;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblProdName;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbldesc;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes1;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet1;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes2;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet2;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes3;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet3;
        
        #line default
        #line hidden
        
        
        #line 102 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes4;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDownloadNow;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDiscount;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFooter1;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblEula;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblPP;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagupdateofferapm.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagUpdateOfferAPM.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pb_Close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.pb_Icon = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.label_heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.label1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.picGraphic = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.tsr_logo = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.lblProdName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.img = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.lbldesc = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.pbBullet = ((System.Windows.Controls.Image)(target));
            return;
            case 11:
            this.lblDes1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.pbBullet1 = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.lblDes2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.pbBullet2 = ((System.Windows.Controls.Image)(target));
            return;
            case 15:
            this.lblDes3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.pbBullet3 = ((System.Windows.Controls.Image)(target));
            return;
            case 17:
            this.lblDes4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.btnDownloadNow = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.btnDiscount = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.lblFooter1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.lblEula = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.txt = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.lblPP = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

