#pragma checksum "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "619E062004CE93195CE00A24ADEC81E2878F67CDA9EE271BCE8BF065115D3C19"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Views.Cloud;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Views.Cloud {
    
    
    /// <summary>
    /// frmMessageDriveAuthorize
    /// </summary>
    public partial class frmMessageDriveAuthorize : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_close;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_close;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_heading;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image gDrive_img;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_heading;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_StepsHeader;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_driveclick;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_drivefill;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_driveadd;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStep1;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStep1Sub;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStep2;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStep2Sub;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStep3;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStep3Sub;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_scan;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_allowpermissions;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/views/cloud/frmmessagedriveauthorize.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Views\Cloud\frmMessageDriveAuthorize.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.img_close = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.lbl_heading = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.gDrive_img = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.txt_heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.txt_StepsHeader = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.img_driveclick = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.img_drivefill = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.img_driveadd = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.txtStep1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.txtStep1Sub = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.txtStep2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.txtStep2Sub = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.txtStep3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.txtStep3Sub = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.btn_scan = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.btn_allowpermissions = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

