using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DuplicatePhotosFixer.Helpers
{
    public static class cTrackingParameters
    {
        public static eProductName activatePathToBuyNow;

        public enum eUTM_BTN_TYPE
        {
            Btn_Sale,
            Btn_ClaimOffer,
            BTN_AutomarkHeader,
            BTN_AutomarkFooter,
            BTN_UnmarkHeader,
            BTN_Notification,
            BTN_AboutUs,
            BTN_ActivateNow,
            BTN_Settings,
            BTN_AddFiles,
            BTN_AddFolder,
            BTN_HomeSettingsOpen,
            BTN_HomeSettingsClose,
            BTN_AddFolderExclude,
            BTN_AddFolderProtected,
            BTN_IncludeFileFolderTab,
            BTN_ExcludeFileFolderTab,
            BTN_ProtectedFoldersTab,
            BTN_CleanNow,
            BTN_LearnMore,
            BTN_ClearFilter,
            BTN_Close,
            BTN_ClickToActivate,
            BTN_CheckForUpdate,
            BTN_Faq,
            BTN_TechnicalSupport,
            BTN_ReturnToStep1,
            DragDropFile,
            BTN_StartScan,
            BTN_StopScan,
            BTN_GoToDuplicates,
            BTN_Back,
            BTN_GoToStartScan,
            BTN_OptionAndSettings,
            BTN_PreviewExpand,
            BTN_PreviewCollapse,
            BTN_ViewAsTable,
            BTN_ViewAsGroup,
            BTN_Undo,
            BTN_DeleteDuplicates,
            BTN_ModifySelection,
            BTN_ManageDuplicates,
            BTN_Purchase,
            BTN_BuyNow,
            BTN_Remove,
            TrialNag_RemoveFirstFreeTrial,
            BTN_Reset,
            BTN_Eula,
            BTN_PrivacyPolicy,
            BTN_UninstallInstructions,
            BTN_Unmark,
            BTN_RefundPolicy,
            BTN_OpenSelectionAssistant,
            BTN_Yes,
            BTN_No,
            BTN_Ok,
            BTN_Retry,
            BTN_Tab,
            CheckBoxIncludeSubFolders,
            BTN_ShowTipOnOff,
            BTN_ExcludeFileType,
            BTN_EnableDisableMaxSize,
            BTN_EnableDisableMinSize,
            BTN_IncludeFileType,
            BTN_GeneralSettingsExpander,
            BTN_LanguageSettingsExpander,

            BTN_SerachFiltersExpander,
            BTN_MoreSearchOptionsExpander,

            BTN_FindFilesWithExpander,
            BTN_AdditionalOptionsExpander,

            BTN_SortBySizeExpander,
            BTN_SortByGroupNumberExpander,

            BTN_Website,

            CheckBox_MatchColumn,
            CheckBox_RegularExpChecked,
            CheckBox_RegularExpUnchecked,
            CheckBox_MatchWholeColumn,
            CheckBox_ShowWelcomeScreen,
            CheckBox_ShowImagesOnTop,
            CheckBox_DisableUpdateCheck,
            CheckBox_LaunchStartUp,
            CheckBox_ConfirmFileDeletion,
            CheckBox_ConfirmReadOnlyFileDeletion,
            CheckBox_ConfirmShowTips,
            CheckBox_ConfirmShowOtherProduct,
            CheckBox_ConfirmShowProductMsg,

            RadioButton_DeleteFilesToBin,
            RadioButton_DeleteFilesToPath,

            Chk_Include,
            BTN_Browse,
            BTN_ExportDuplicateList,
            BTN_ClearCache,
            BTN_Apply,
            BTN_Restore,

            BTN_IncludedTab,
            BTN_ExcludedTab,

            BTN_StartOneDayTrial,
            BTN_StartOneDayNext,
            BTN_Add,
            BTN_Delete,
            BTN_Edit,
            BTN_Update,

            BTN_AddInclude,
            BTN_AddExclude,
            BTN_DeleteInclude,
            BTN_DeleteExclude,
            BTN_EditInclude,
            BTN_EditExclude,

            BTN_AddIncludeFileType,
            BTN_AddExcludeFileType,
            BTN_EditIncludeFileType,
            BTN_EditExcludeFileType,
            BTN_DeleteIncludeFileType,
            BTN_DeleteExcludeFileType,

            BTN_Mark,
            BTN_Cancel,
            BTN_ResetSelectionPriority,

            BTN_UpArrow,
            BTN_DownArrow,

            RadioButton_AnyDate,
            RadioButton_Created,
            RadioButton_Modified,

            ComboBox_From,
            ComboBox_To,

            CheckBox_AnySize,
            ComboBox_MinFileSizeUnit,
            ComboBox_MaxFileSizeUnit,
            NumericTextBox_MaxFileSize,
            NumericTextBox_MinFileSize,

            CheckBox_ExcludeZerosizeFileFromDuplicatelist,
            CheckBox_ExcludeLessthan1KBSizeFileFromDuplicatelist,
            CheckBox_ExcludeLessthan10KBSizeFileFromDuplicatelist,

            BTN_LoadResult,
            RadioButton_SameContent,
            RadioButton_IgnoreContent,

            CheckBox_SameFileName,
            CheckBox_SimilerFileNames,
            CheckBox_SameFileSize,
            CheckBox_SameCreatedDate,
            CheckBox_ScanHiddenFolderFiles,
            CheckBox_SameModifiedDate,

            CheckBox_DateModified,
            CheckBox_FileCreated,
            CheckBox_Folder,
            CheckBox_Size,
            CheckBox_FileFormat,
            CheckBox_DoNotShow,
            CheckBox_IncludeSubFolder,

            NumericTextBox_DateModified,
            NumericTextBox_FileCreated,
            NumericTextBox_Folder,
            NumericTextBox_Size,
            NumericTextBox_FileFormat,

            BTN_GetStarted,
            BTN_UpgradeNow,
            BTN_PruchaseNext,
            BTN_ContinueTrialNext,
            BTN_RegisterNow,
            BTN_Exit,
            BTN_ReturnToApp,
            BTN_EnterLicenseKey,
            BTN_ReturnToTrialMode,

            BTN_PasteLicenseKey,

            BTN_InstallNow,
            BTN_InstallNotRegsitered,
            BTN_LaunchNow,
            BTN_CancelInstall,

            CheckBox_MarkHeaderFile,
            CheckBox_MarkChildFile,
            CheckBox_UnmarkHeaderFile,
            CheckBox_UnmarkChildFile,
            Expander_PreviewFiles,
            BTN_AllFiles,
            BTN_Documents,
            BTN_Pictures,
            BTN_Music,
            BTN_Videos,
            BTN_OtherFiles,
            BTN_Rescan,

            SelectFolderAndFilesTab,
            ScanProgressTab,
            LastScanReportTab,
            CleanDuplicatesTab,
            SelectionAssistant,
            MenuItem_Automark,
            MenuItem_Automark_Options,
            MenuItem_Mark,
            MenuItem_MarkAllFilesType,
            MenuItem_MarkAllFilesFolder,
            MenuItem_MarkAllFilesFolderTree,
            MenuItem_MarkAllFilesDuplicatesThisFolderElsewhere,
            MenuItem_UnmarkAll,
            MenuItem_UnMarkAllFilesType,
            MenuItem_UnMarkAllFilesFolder,
            MenuItem_UnMarkAllFilesFoldertree,
            MenuItem_UnMarkAllFilesDuplicatesThisFolderElsewhere,
            MenuItem_MarkIt,
            MenuItem_UnMarkIt,
            MenuItem_Unmark,
            MenuItem_AutomarkProtection,
            MenuItem_ProtectFolder,
            MenuItem_ProtectParentFolder,
            MenuItem_InvertMarkedFiles,
            MenuItem_FilterGroupsMarkedFile,
            MenuItem_FilterThisGroup,
            MenuItem_ClearAllFilters,
            MenuItem_ThisFileDoesNotBelongtothisGroupRemoveFromGroup,
            MenuItem_MergetheseGroups,
            MenuItem_RemovefileSizeResults,
            MenuItem_ExcludeFolder,
            MenuItem_DeleteSelected,
            MenuItem_ExportDuplicateList,
            MenuItem_ClearResolvedDuplicatesFromList,
            MenuItem_ClearCache,
            MenuItem_ShowAllFiles,
            MenuItem_HideDeletedFiles,
            MenuItem_ShowOnlyDeletedFiles,
            MenuItem_RefreshForDeletedFiles,
            MenuItem_DeleteThisFile,
            MenuItem_AllButOneInEachGroup,
            MenuItem_MarkByCreatedDateOldestFileInEachGroup,
            MenuItem_MarkByCreatedDateNewestFileInEachGroup,
            MenuItem_MarkByModifiedDateOldestFileInEachGroup,
            MenuItem_MarkByModifiedDateNewestFileInEachGroup,
            MenuItem_MarkByFileSizeSmallestFileInEachGroup,
            MenuItem_MarkByFileSizeLargestFileInEachGroup,
            MenuItem_MarkByFileNameLengthShortestFileInEachGroup,
            MenuItem_MarkByFileNameLengthLongestFileInEachGroup,
            MenuItem_MarkByFilePathLengthShortestPathInEachGroup,
            MenuItem_MarkByFilePathLengthLongestPathInEachGroup,
            Show,
            Close,
            OpenAppSettings_General,

            SystemTrayContextMenu_Exit,
            SystemTrayContextMenu_OpenWIndow,

            SelectSystemScanMode,
            SelectGoogleScanMode,
            SelectDropboxScanMode,
            SelectMobileSmartScanMode,
            BTN_Feedback,
        }

        public enum eProductName
        {
            StoreBuyNowWindow,
            SelectionAssistant,
            UninstallDiscountNag,
            MainWindow,
            AfterUpdateNewFeatures,
            ModifySelectionButton,
            ActivateNowTab,
            ActivateNow_Home_Window,
            ActionCenterTab,
            OptionsAndSettingTab,
            SelectFolderAndFilesTab,
            SelectScanMode,
            StartScanTab,
            ScanCompleteTab,
            ScanProgressTab,
            ScanResultTab,
            SettingsPanel,
            ActivationWindow,
            AboutUsWindow,
            InstallUtilityWindow,
            InstallUtilityWindowBuyNow,
            SearchFilterWindow,
            SearchLocationWindow,
            DeleteFileWindow,
            ErrorUndoWindow,
            HomeExtenisonListIncludeWindow,
            HomeExtenisonListExcludeWindow,
            SettingsExtensionListIncludeWindow,
            SettingsExtensionListExcludeWindow,
            HomeFileTypeIncludeWindow,
            HomeFileTypeExcludeWindow,
            RemoveDuplicateWindow,
            UpdatorWindow,
            MsgBoxWithCheckBoxWindow,
            IncludeFileFolderTab,
            ExcludeFileFolderTab,
            ProtectedFoldersTab,
            SettingsWindow,
            GeneralSettingsTab,
            AdvanceScanSettingsTab,
            SearchOptionsTab,
            ScanHistoryTab,

            Expander_GeneralSettings,
            Expander_LanguageSettings,

            SerachFiltersExpander,
            MoreSearchOptionsExpander,

            FindFilesWithExpander,
            AdditionalOptionsExpander,

            SelectionAssistantWindow,
            GeneralFromSelectionAssistantTab,
            ProtectedFoldersFromSelectionAssistantTab,
            FileFormatsFromSelectionAssistantTab,
            FoldersFromSelectionAssistantTab,
            ActionCenterWindow,

            IncludedTab,
            ExcludedTab,

            StartUpNag,
            ExitNag,
            NagFreeTrialVersionDFF,
            NagAlertForFreeVersionLimit,
            NagUpgradeFullversion,

            NagTwentyFourHours,
            NagTrayOffer,
            NagTaskbarNotification,
            NagOneDay,
            NagCleanFiles,
            NagTrayUpgradgeNow,
            FreeTrial24TrayNag,
            FreeTrial24TrayNagExpired,
            FreeTrial24ExpireNag,
            After24HourTrialClean,
            StartFreeTrialOneDay,
            ADUOffer,
            RCPOffer,
            ASPOffer,
            McAfeeOffer,

            NagTrial,
            NagExitOffer,

            UpdateOffer,
            UpdateOfferNew,
            UpdateOfferTweakShot,
            UpdateOfferTSR,

            SystemTrayContextMenu
        }

        public enum eReminderEventType
        {
            show = 1,
            close,
            actionbuttonprimary,
            actionbuttonsecondary,
            other
        }

        public enum eReminderOfferType
        {
            AppPurchaseOffer = 1,
            CrossPromotionOffer,
            ThirdPartyOffer
        }
    }
}
