#pragma checksum "..\..\..\UserControls\ucGeneralSettings.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "900BDB577BB583009C9C1EED1154DC7FC6994032C30A5078FD39EA33D418F018"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.UserControls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.UserControls {
    
    
    /// <summary>
    /// ucGeneralSettings
    /// </summary>
    public partial class ucGeneralSettings : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 15 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGeneral;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkConfirmdeleteDlg;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtConfirmdeleteDlg;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkAutoMarkDlg;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtAutoMarkDlg;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkConfirmBackDlg;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtConfirmBackDlg;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\UserControls\ucGeneralSettings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_resetdefault;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/usercontrols/ucgeneralsettings.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UserControls\ucGeneralSettings.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.lblGeneral = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.chkConfirmdeleteDlg = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.txtConfirmdeleteDlg = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.chkAutoMarkDlg = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.txtAutoMarkDlg = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.chkConfirmBackDlg = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.txtConfirmBackDlg = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.btn_resetdefault = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

