#pragma checksum "..\..\..\Nags\nagUpdateOfferTweakshot.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "551E0DB0C6C54563C80F7DB56ED040FBC8E308EA7A8064AB3B9FD6D724DE9BB4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagUpdateOfferTweakshot
    /// </summary>
    public partial class nagUpdateOfferTweakshot : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pb_Close;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_Icon;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label_heading;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_Image;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblProdName;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes1;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDescInfo1;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet1;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes2;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDescInfo2;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet2;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes3;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDescInfo3;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbBullet3;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDes4;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDescInfo4;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_buynow;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_install;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblLinksInfo;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblEula;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblPP;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagupdateoffertweakshot.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagUpdateOfferTweakshot.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pb_Close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.pb_Icon = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.label_heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.pb_Image = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.lblProdName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.pbBullet = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.lblDes1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.lblDescInfo1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.pbBullet1 = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.lblDes2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.lblDescInfo2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.pbBullet2 = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.lblDes3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.lblDescInfo3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.pbBullet3 = ((System.Windows.Controls.Image)(target));
            return;
            case 16:
            this.lblDes4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.lblDescInfo4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.btn_buynow = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.btn_install = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.lblLinksInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.lblEula = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.txt = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.lblPP = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

