#pragma checksum "..\..\..\Nags\nagUpdateOffer_New.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2515D388272394249D784E02E5C5E178BE8FB13111AC546527EFC71A2F288EA1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagUpdateOffer_New
    /// </summary>
    public partial class nagUpdateOffer_New : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 18 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button pb_Close;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_Icon;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label_heading;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label1;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label2;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label3;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Install;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFooter1;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblFooter2;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink lblEula;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink lblPP;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pb_Image;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image pbInfo;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt1;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt2;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\Nags\nagUpdateOffer_New.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt3;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagupdateoffer_new.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagUpdateOffer_New.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pb_Close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.pb_Icon = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.label_heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.label1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.label2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.label3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.btn_Install = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.lblFooter1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.lblFooter2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.lblEula = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 11:
            this.lblPP = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 12:
            this.pb_Image = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.pbInfo = ((System.Windows.Controls.Image)(target));
            return;
            case 14:
            this.txt1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.txt2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.txt3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

