#pragma checksum "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "04B2FC387B16224B85E914C6A51DA771F4DF6973F0CD6D9A569DDC91F0499336"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagMessageEmailDuplicateCount
    /// </summary>
    public partial class nagMessageEmailDuplicateCount : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image info_img;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock rtb_totalPhotos;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock rtb_totlaSize;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label4;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label3;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label5;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock pnl_name;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_email;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock llNoThanks;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnFreeLic;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagmessageemailduplicatecount.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagMessageEmailDuplicateCount.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.info_img = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.rtb_totalPhotos = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.rtb_totlaSize = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.label4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.label3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.label5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.pnl_name = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.txt_email = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.llNoThanks = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.btnFreeLic = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

