#pragma checksum "..\..\..\Nags\frmTrayNagOffer.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CCB2A1233AD1479BC6558426EC74F6768840AAC331CFBA838BC42FE0E76E8894"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// frmTrayNagOffer
    /// </summary>
    public partial class frmTrayNagOffer : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_close;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_title;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_limitedOffer;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock cLabel1;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_mbc;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_discValue;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_discount;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_claimOffer;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock llbl_removeAll;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox cbox_notShowAgain;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\Nags\frmTrayNagOffer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ms_logo;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/frmtraynagoffer.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\frmTrayNagOffer.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.lbl_title = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.lbl_limitedOffer = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.cLabel1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.img_mbc = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.lbl_discValue = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.lbl_discount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.btn_claimOffer = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.llbl_removeAll = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.cbox_notShowAgain = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.ms_logo = ((System.Windows.Controls.Image)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

