#pragma checksum "..\..\..\Nags\nagCooldown.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "52DE0FF8E846E5F569569E91F5FD293D374C9521A1BB0A56F54F9E31CF61674A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagCooldown
    /// </summary>
    public partial class nagCooldown : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_close;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_attention;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock linklabel1;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image clock_img;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_dupsCount;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_counter;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_totalSpace;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_removeLimit;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_mbc;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_upgradeNow;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl1;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_haveLicenceKey;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock llink_haveKey;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\Nags\nagCooldown.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_upgradeNow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagcooldown.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagCooldown.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.lbl_attention = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.linklabel1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.clock_img = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.lbl_dupsCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.lbl_counter = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.lbl_totalSpace = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.btn_removeLimit = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.img_mbc = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.lbl_upgradeNow = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.lbl1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.lbl_haveLicenceKey = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.llink_haveKey = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.btn_upgradeNow = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

