#pragma checksum "..\..\..\UserControls\ucpromotionalADU.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3101A44D52829DED78D5D068E74ED9019E2EC39F4C96F5F28F8F8CE379DF8AA7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.UserControls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.UserControls {
    
    
    /// <summary>
    /// ucpromotionalADU
    /// </summary>
    public partial class ucpromotionalADU : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image arrow_img;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl1;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image divider;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ADU_img;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Product_heading;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock product_info;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image tick_img;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock product_des1;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image tick_img1;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock product_des2;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image tick_img2;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock product_des3;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image tick_img3;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock product_des4;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button install_btn;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button cancel_btn;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_agree;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EULA_btn;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\UserControls\ucpromotionalADU.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PrivacyPolicy_btn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/usercontrols/ucpromotionaladu.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UserControls\ucpromotionalADU.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.arrow_img = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.lbl1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.divider = ((System.Windows.Controls.Image)(target));
            return;
            case 4:
            this.ADU_img = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.Product_heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.product_info = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.tick_img = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.product_des1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.tick_img1 = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.product_des2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.tick_img2 = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.product_des3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.tick_img3 = ((System.Windows.Controls.Image)(target));
            return;
            case 14:
            this.product_des4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.install_btn = ((System.Windows.Controls.Button)(target));
            return;
            case 16:
            this.cancel_btn = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.lbl_agree = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.EULA_btn = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.lbl = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.PrivacyPolicy_btn = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

