#pragma checksum "..\..\..\Nags\nagTrialExpire.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3B9DF74BE09AD680CDA98503B7309FD88348651B10A1D1FC8C1BF15B80B15A7F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagTrialExpire
    /// </summary>
    public partial class nagTrialExpire : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_close;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblExpire;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock text_registration;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick1;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt1;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick2;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt2;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick3;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt3;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick4;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt4;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick5;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt5;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image limited_offer_img;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_mb;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt6;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\Nags\nagTrialExpire.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt7;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagtrialexpire.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagTrialExpire.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.lblExpire = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.text_registration = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.img_tick1 = ((System.Windows.Controls.Image)(target));
            return;
            case 5:
            this.txt1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.img_tick2 = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.txt2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.img_tick3 = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.txt3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.img_tick4 = ((System.Windows.Controls.Image)(target));
            return;
            case 11:
            this.txt4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.img_tick5 = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.txt5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.limited_offer_img = ((System.Windows.Controls.Image)(target));
            return;
            case 15:
            this.img_mb = ((System.Windows.Controls.Image)(target));
            return;
            case 16:
            this.txt6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.txt7 = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

