#pragma checksum "..\..\..\Nags\nagNewTheamUpgradeNow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "4770327E7B42CA7295B8A44FD2D9040C83F66AA95A6361440E561134EF331DA1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagNewTheamUpgradeNow
    /// </summary>
    public partial class nagNewTheamUpgradeNow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_close;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label1;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDupPhotos;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label2;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblSpace;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label3;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink llUpgradeNow;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink llAlreadyKey;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_block;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick1;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt1;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick2;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt2;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick3;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt3;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick4;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt4;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpgrade;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_mb;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt5;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt6;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnContinueUn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagnewtheamupgradenow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagNewTheamUpgradeNow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.img = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.label = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.label1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.lblDupPhotos = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.label2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.lblSpace = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.label3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.llUpgradeNow = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 10:
            this.llAlreadyKey = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 11:
            this.txt_block = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.img_tick1 = ((System.Windows.Controls.Image)(target));
            return;
            case 13:
            this.txt1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.img_tick2 = ((System.Windows.Controls.Image)(target));
            return;
            case 15:
            this.txt2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.img_tick3 = ((System.Windows.Controls.Image)(target));
            return;
            case 17:
            this.txt3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.img_tick4 = ((System.Windows.Controls.Image)(target));
            return;
            case 19:
            this.txt4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.btnUpgrade = ((System.Windows.Controls.Button)(target));
            return;
            case 21:
            this.img_mb = ((System.Windows.Controls.Image)(target));
            return;
            case 22:
            this.txt5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.txt6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.btnContinueUn = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

