#pragma checksum "..\..\..\Nags\nagNewTheamEmail2.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0C5BA655CCBEBD9E2880412B6B05807B02C83FDBB23587DE8BB546DF0CC6529C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagNewTheamEmail2
    /// </summary>
    public partial class nagNewTheamEmail2 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 18 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_close;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label1;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblDupPhotos;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label2;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblSpace;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label3;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_mb;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt5;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt6;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_block1;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_block2;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink llEnterKey;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGetFullVer;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\Nags\nagNewTheamEmail2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpgNow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagnewtheamemail2.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagNewTheamEmail2.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btn_close = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.img = ((System.Windows.Controls.Image)(target));
            return;
            case 3:
            this.label1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.lblDupPhotos = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.label2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.lblSpace = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.label3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.img_mb = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.txt5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.txt6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.txt_block1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.txt_block2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.llEnterKey = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 14:
            this.btnGetFullVer = ((System.Windows.Controls.Button)(target));
            return;
            case 15:
            this.btnUpgNow = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

