//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DuplicatePhotosFixer.STGenuineValidator
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "STGenuineValidationServiceSoap", Namespace = "http://systweak.com/")]
public partial class STGenuineValidationService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback STIsSoftwareGenuineOperationCompleted;

    private System.Threading.SendOrPostCallback STIsKeyGenuineOperationCompleted;

    private System.Threading.SendOrPostCallback STIsCurKeyNeedToExpireOperationCompleted;

    private System.Threading.SendOrPostCallback STGetSoftwareCheckUpdateURLOperationCompleted;

    private System.Threading.SendOrPostCallback STCheckGenuinenessOperationCompleted;

    private bool useDefaultCredentialsSetExplicitly;

    /// <remarks/>
    public STGenuineValidationService()
    {
        //this.Url = global::DuplicatePhotosFixer.Properties.Settings.Default.DuplicatePhotosFixerPro_STGenuineValidator_STGenuineValidationService;
        if ((this.IsLocalFileSystemWebService(this.Url) == true))
        {
            this.UseDefaultCredentials = true;
            this.useDefaultCredentialsSetExplicitly = false;
        }
        else
        {
            this.useDefaultCredentialsSetExplicitly = true;
        }
    }

    public new string Url
    {
        get
        {
            return base.Url;
        }
        set
        {
            if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                        && (this.useDefaultCredentialsSetExplicitly == false))
                        && (this.IsLocalFileSystemWebService(value) == false)))
            {
                base.UseDefaultCredentials = false;
            }
            base.Url = value;
        }
    }

    public new bool UseDefaultCredentials
    {
        get
        {
            return base.UseDefaultCredentials;
        }
        set
        {
            base.UseDefaultCredentials = value;
            this.useDefaultCredentialsSetExplicitly = true;
        }
    }

    /// <remarks/>
    public event STIsSoftwareGenuineCompletedEventHandler STIsSoftwareGenuineCompleted;

    /// <remarks/>
    public event STIsKeyGenuineCompletedEventHandler STIsKeyGenuineCompleted;

    /// <remarks/>
    public event STIsCurKeyNeedToExpireCompletedEventHandler STIsCurKeyNeedToExpireCompleted;

    /// <remarks/>
    public event STGetSoftwareCheckUpdateURLCompletedEventHandler STGetSoftwareCheckUpdateURLCompleted;

    /// <remarks/>
    public event STCheckGenuinenessCompletedEventHandler STCheckGenuinenessCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://systweak.com/STIsSoftwareGenuine", RequestNamespace = "http://systweak.com/", ResponseNamespace = "http://systweak.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string STIsSoftwareGenuine(ServiceInput srvInput)
    {
        object[] results = this.Invoke("STIsSoftwareGenuine", new object[] {
                        srvInput});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void STIsSoftwareGenuineAsync(ServiceInput srvInput)
    {
        this.STIsSoftwareGenuineAsync(srvInput, null);
    }

    /// <remarks/>
    public void STIsSoftwareGenuineAsync(ServiceInput srvInput, object userState)
    {
        if ((this.STIsSoftwareGenuineOperationCompleted == null))
        {
            this.STIsSoftwareGenuineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTIsSoftwareGenuineOperationCompleted);
        }
        this.InvokeAsync("STIsSoftwareGenuine", new object[] {
                        srvInput}, this.STIsSoftwareGenuineOperationCompleted, userState);
    }

    private void OnSTIsSoftwareGenuineOperationCompleted(object arg)
    {
        if ((this.STIsSoftwareGenuineCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.STIsSoftwareGenuineCompleted(this, new STIsSoftwareGenuineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://systweak.com/STIsKeyGenuine", RequestNamespace = "http://systweak.com/", ResponseNamespace = "http://systweak.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string STIsKeyGenuine(ServiceInput srvInput)
    {
        object[] results = this.Invoke("STIsKeyGenuine", new object[] {
                        srvInput});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void STIsKeyGenuineAsync(ServiceInput srvInput)
    {
        this.STIsKeyGenuineAsync(srvInput, null);
    }

    /// <remarks/>
    public void STIsKeyGenuineAsync(ServiceInput srvInput, object userState)
    {
        if ((this.STIsKeyGenuineOperationCompleted == null))
        {
            this.STIsKeyGenuineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTIsKeyGenuineOperationCompleted);
        }
        this.InvokeAsync("STIsKeyGenuine", new object[] {
                        srvInput}, this.STIsKeyGenuineOperationCompleted, userState);
    }

    private void OnSTIsKeyGenuineOperationCompleted(object arg)
    {
        if ((this.STIsKeyGenuineCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.STIsKeyGenuineCompleted(this, new STIsKeyGenuineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://systweak.com/STIsCurKeyNeedToExpire", RequestNamespace = "http://systweak.com/", ResponseNamespace = "http://systweak.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string STIsCurKeyNeedToExpire(ServiceInput srvInput)
    {
        object[] results = this.Invoke("STIsCurKeyNeedToExpire", new object[] {
                        srvInput});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void STIsCurKeyNeedToExpireAsync(ServiceInput srvInput)
    {
        this.STIsCurKeyNeedToExpireAsync(srvInput, null);
    }

    /// <remarks/>
    public void STIsCurKeyNeedToExpireAsync(ServiceInput srvInput, object userState)
    {
        if ((this.STIsCurKeyNeedToExpireOperationCompleted == null))
        {
            this.STIsCurKeyNeedToExpireOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTIsCurKeyNeedToExpireOperationCompleted);
        }
        this.InvokeAsync("STIsCurKeyNeedToExpire", new object[] {
                        srvInput}, this.STIsCurKeyNeedToExpireOperationCompleted, userState);
    }

    private void OnSTIsCurKeyNeedToExpireOperationCompleted(object arg)
    {
        if ((this.STIsCurKeyNeedToExpireCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.STIsCurKeyNeedToExpireCompleted(this, new STIsCurKeyNeedToExpireCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://systweak.com/STGetSoftwareCheckUpdateURL", RequestNamespace = "http://systweak.com/", ResponseNamespace = "http://systweak.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string STGetSoftwareCheckUpdateURL(ServiceInput srvInput)
    {
        object[] results = this.Invoke("STGetSoftwareCheckUpdateURL", new object[] {
                        srvInput});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void STGetSoftwareCheckUpdateURLAsync(ServiceInput srvInput)
    {
        this.STGetSoftwareCheckUpdateURLAsync(srvInput, null);
    }

    /// <remarks/>
    public void STGetSoftwareCheckUpdateURLAsync(ServiceInput srvInput, object userState)
    {
        if ((this.STGetSoftwareCheckUpdateURLOperationCompleted == null))
        {
            this.STGetSoftwareCheckUpdateURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTGetSoftwareCheckUpdateURLOperationCompleted);
        }
        this.InvokeAsync("STGetSoftwareCheckUpdateURL", new object[] {
                        srvInput}, this.STGetSoftwareCheckUpdateURLOperationCompleted, userState);
    }

    private void OnSTGetSoftwareCheckUpdateURLOperationCompleted(object arg)
    {
        if ((this.STGetSoftwareCheckUpdateURLCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.STGetSoftwareCheckUpdateURLCompleted(this, new STGetSoftwareCheckUpdateURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://systweak.com/STCheckGenuineness", RequestNamespace = "http://systweak.com/", ResponseNamespace = "http://systweak.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string STCheckGenuineness(ServiceInput srvInput)
    {
        object[] results = this.Invoke("STCheckGenuineness", new object[] {
                        srvInput});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void STCheckGenuinenessAsync(ServiceInput srvInput)
    {
        this.STCheckGenuinenessAsync(srvInput, null);
    }

    /// <remarks/>
    public void STCheckGenuinenessAsync(ServiceInput srvInput, object userState)
    {
        if ((this.STCheckGenuinenessOperationCompleted == null))
        {
            this.STCheckGenuinenessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCheckGenuinenessOperationCompleted);
        }
        this.InvokeAsync("STCheckGenuineness", new object[] {
                        srvInput}, this.STCheckGenuinenessOperationCompleted, userState);
    }

    private void OnSTCheckGenuinenessOperationCompleted(object arg)
    {
        if ((this.STCheckGenuinenessCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.STCheckGenuinenessCompleted(this, new STCheckGenuinenessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }

    private bool IsLocalFileSystemWebService(string url)
    {
        if (((url == null)
                    || (url == string.Empty)))
        {
            return false;
        }
        System.Uri wsUri = new System.Uri(url);
        if (((wsUri.Port >= 1024)
                    && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
        {
            return true;
        }
        return false;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://systweak.com/")]
public partial class ServiceInput
{

    private int callFnsField;

    private Install_App_Info installedApplicationInfoField;

    private ProductGenuineCheckInput[] productGenuineCheckInputDataField;

    /// <remarks/>
    public int CallFns
    {
        get
        {
            return this.callFnsField;
        }
        set
        {
            this.callFnsField = value;
        }
    }

    /// <remarks/>
    public Install_App_Info InstalledApplicationInfo
    {
        get
        {
            return this.installedApplicationInfoField;
        }
        set
        {
            this.installedApplicationInfoField = value;
        }
    }

    /// <remarks/>
    public ProductGenuineCheckInput[] ProductGenuineCheckInputData
    {
        get
        {
            return this.productGenuineCheckInputDataField;
        }
        set
        {
            this.productGenuineCheckInputDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://systweak.com/")]
public partial class Install_App_Info
{

    private short app_identifierField;

    private string client_identifierField;

    private string cur_program_versionField;

    private string requestDateTimeField;

    private string user_activation_codeField;

    private string user_nameField;

    private string user_email_addrField;

    private string user_license_keyField;

    private string user_machine_idField;

    private short key_validdaysField;

    private short keyInstalledDaysField;

    private string lang_codeField;

    private short lang_idField;

    private int rEGISTRATION_STATUSField;

    private int nRequestFlagsField;

    private short isRetailKeyField;

    private string utm_sourceField;

    private string utm_mediumField;

    private string utm_contentField;

    private string utm_termField;

    private string keyForField;

    private int nReserved1Field;

    private int nReserved2Field;

    private int nReserved3Field;

    private int nReserved4Field;

    private int nReserved5Field;

    private string sReserved1Field;

    private string sReserved2Field;

    private string sReserved3Field;

    private string sReserved4Field;

    private string sReserved5Field;

    /// <remarks/>
    public short app_identifier
    {
        get
        {
            return this.app_identifierField;
        }
        set
        {
            this.app_identifierField = value;
        }
    }

    /// <remarks/>
    public string client_identifier
    {
        get
        {
            return this.client_identifierField;
        }
        set
        {
            this.client_identifierField = value;
        }
    }

    /// <remarks/>
    public string cur_program_version
    {
        get
        {
            return this.cur_program_versionField;
        }
        set
        {
            this.cur_program_versionField = value;
        }
    }

    /// <remarks/>
    public string requestDateTime
    {
        get
        {
            return this.requestDateTimeField;
        }
        set
        {
            this.requestDateTimeField = value;
        }
    }

    /// <remarks/>
    public string user_activation_code
    {
        get
        {
            return this.user_activation_codeField;
        }
        set
        {
            this.user_activation_codeField = value;
        }
    }

    /// <remarks/>
    public string user_name
    {
        get
        {
            return this.user_nameField;
        }
        set
        {
            this.user_nameField = value;
        }
    }

    /// <remarks/>
    public string user_email_addr
    {
        get
        {
            return this.user_email_addrField;
        }
        set
        {
            this.user_email_addrField = value;
        }
    }

    /// <remarks/>
    public string user_license_key
    {
        get
        {
            return this.user_license_keyField;
        }
        set
        {
            this.user_license_keyField = value;
        }
    }

    /// <remarks/>
    public string user_machine_id
    {
        get
        {
            return this.user_machine_idField;
        }
        set
        {
            this.user_machine_idField = value;
        }
    }

    /// <remarks/>
    public short key_validdays
    {
        get
        {
            return this.key_validdaysField;
        }
        set
        {
            this.key_validdaysField = value;
        }
    }

    /// <remarks/>
    public short KeyInstalledDays
    {
        get
        {
            return this.keyInstalledDaysField;
        }
        set
        {
            this.keyInstalledDaysField = value;
        }
    }

    /// <remarks/>
    public string lang_code
    {
        get
        {
            return this.lang_codeField;
        }
        set
        {
            this.lang_codeField = value;
        }
    }

    /// <remarks/>
    public short lang_id
    {
        get
        {
            return this.lang_idField;
        }
        set
        {
            this.lang_idField = value;
        }
    }

    /// <remarks/>
    public int REGISTRATION_STATUS
    {
        get
        {
            return this.rEGISTRATION_STATUSField;
        }
        set
        {
            this.rEGISTRATION_STATUSField = value;
        }
    }

    /// <remarks/>
    public int nRequestFlags
    {
        get
        {
            return this.nRequestFlagsField;
        }
        set
        {
            this.nRequestFlagsField = value;
        }
    }

    /// <remarks/>
    public short IsRetailKey
    {
        get
        {
            return this.isRetailKeyField;
        }
        set
        {
            this.isRetailKeyField = value;
        }
    }

    /// <remarks/>
    public string utm_source
    {
        get
        {
            return this.utm_sourceField;
        }
        set
        {
            this.utm_sourceField = value;
        }
    }

    /// <remarks/>
    public string utm_medium
    {
        get
        {
            return this.utm_mediumField;
        }
        set
        {
            this.utm_mediumField = value;
        }
    }

    /// <remarks/>
    public string utm_content
    {
        get
        {
            return this.utm_contentField;
        }
        set
        {
            this.utm_contentField = value;
        }
    }

    /// <remarks/>
    public string utm_term
    {
        get
        {
            return this.utm_termField;
        }
        set
        {
            this.utm_termField = value;
        }
    }

    /// <remarks/>
    public string KeyFor
    {
        get
        {
            return this.keyForField;
        }
        set
        {
            this.keyForField = value;
        }
    }

    /// <remarks/>
    public int nReserved1
    {
        get
        {
            return this.nReserved1Field;
        }
        set
        {
            this.nReserved1Field = value;
        }
    }

    /// <remarks/>
    public int nReserved2
    {
        get
        {
            return this.nReserved2Field;
        }
        set
        {
            this.nReserved2Field = value;
        }
    }

    /// <remarks/>
    public int nReserved3
    {
        get
        {
            return this.nReserved3Field;
        }
        set
        {
            this.nReserved3Field = value;
        }
    }

    /// <remarks/>
    public int nReserved4
    {
        get
        {
            return this.nReserved4Field;
        }
        set
        {
            this.nReserved4Field = value;
        }
    }

    /// <remarks/>
    public int nReserved5
    {
        get
        {
            return this.nReserved5Field;
        }
        set
        {
            this.nReserved5Field = value;
        }
    }

    /// <remarks/>
    public string sReserved1
    {
        get
        {
            return this.sReserved1Field;
        }
        set
        {
            this.sReserved1Field = value;
        }
    }

    /// <remarks/>
    public string sReserved2
    {
        get
        {
            return this.sReserved2Field;
        }
        set
        {
            this.sReserved2Field = value;
        }
    }

    /// <remarks/>
    public string sReserved3
    {
        get
        {
            return this.sReserved3Field;
        }
        set
        {
            this.sReserved3Field = value;
        }
    }

    /// <remarks/>
    public string sReserved4
    {
        get
        {
            return this.sReserved4Field;
        }
        set
        {
            this.sReserved4Field = value;
        }
    }

    /// <remarks/>
    public string sReserved5
    {
        get
        {
            return this.sReserved5Field;
        }
        set
        {
            this.sReserved5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://systweak.com/")]
public partial class ProductGenuineCheckInput
{

    private string filePathField;

    private string hashField;

    /// <remarks/>
    public string FilePath
    {
        get
        {
            return this.filePathField;
        }
        set
        {
            this.filePathField = value;
        }
    }

    /// <remarks/>
    public string Hash
    {
        get
        {
            return this.hashField;
        }
        set
        {
            this.hashField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
public delegate void STIsSoftwareGenuineCompletedEventHandler(object sender, STIsSoftwareGenuineCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class STIsSoftwareGenuineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal STIsSoftwareGenuineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
public delegate void STIsKeyGenuineCompletedEventHandler(object sender, STIsKeyGenuineCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class STIsKeyGenuineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal STIsKeyGenuineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
public delegate void STIsCurKeyNeedToExpireCompletedEventHandler(object sender, STIsCurKeyNeedToExpireCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class STIsCurKeyNeedToExpireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal STIsCurKeyNeedToExpireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
public delegate void STGetSoftwareCheckUpdateURLCompletedEventHandler(object sender, STGetSoftwareCheckUpdateURLCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class STGetSoftwareCheckUpdateURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal STGetSoftwareCheckUpdateURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
public delegate void STCheckGenuinenessCompletedEventHandler(object sender, STCheckGenuinenessCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class STCheckGenuinenessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal STCheckGenuinenessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
}

#pragma warning restore 1591