#pragma checksum "..\..\..\Views\frmProgress.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "6B7538109DAABB3C8AF85E4CF1DBEEC34B008CF85A166CA2D2ED1D7797382718"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Views;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Views {
    
    
    /// <summary>
    /// frmProgress
    /// </summary>
    public partial class frmProgress : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_percentage;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_searchingDuplicates;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image scanBar_progress;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_progressInfo;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image scanBar;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_yes;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Cancel;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_outdate;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\Views\frmProgress.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_infoRaw;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/views/frmprogress.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\frmProgress.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.lbl_percentage = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.lbl_searchingDuplicates = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.scanBar_progress = ((System.Windows.Controls.Image)(target));
            return;
            case 4:
            this.lbl_progressInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.scanBar = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.btn_yes = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.btn_Cancel = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.img_outdate = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.lbl_infoRaw = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

