#pragma checksum "..\..\..\Nags\nagVistaEmail.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "3265041E8607FC6920B13150A75458F597562623956FE1466AAEA1015922EAAC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.Nags;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.Nags {
    
    
    /// <summary>
    /// nagVistaEmail
    /// </summary>
    public partial class nagVistaEmail : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_popup;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock heading;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock rtb_TopText;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt_block;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick1;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt1;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick2;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt2;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick3;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt3;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img_tick4;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt4;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGetFullVer;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txt0;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpgrade;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock key;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink llAlreadyKey;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_contUnreg;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_details;
        
        #line default
        #line hidden
        
        
        #line 159 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image dropdown_arrow;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label6;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock label;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\..\Nags\nagVistaEmail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock richTextBoxEx1;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/nags/nagvistaemail.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Nags\nagVistaEmail.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.img_popup = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.heading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.rtb_TopText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.txt_block = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.img_tick1 = ((System.Windows.Controls.Image)(target));
            return;
            case 6:
            this.txt1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.img_tick2 = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.txt2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.img_tick3 = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.txt3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.img_tick4 = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.txt4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.btnGetFullVer = ((System.Windows.Controls.Button)(target));
            return;
            case 14:
            this.txt = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.txt0 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.btnUpgrade = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.key = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.llAlreadyKey = ((System.Windows.Documents.Hyperlink)(target));
            return;
            case 19:
            this.btn_contUnreg = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.btn_details = ((System.Windows.Controls.Button)(target));
            return;
            case 21:
            this.dropdown_arrow = ((System.Windows.Controls.Image)(target));
            return;
            case 22:
            this.label6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.label = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.richTextBoxEx1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

