#pragma checksum "..\..\..\UserControls\ucResultObjectListView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "ED7F4ADD2D849AF8559BD5E2E202EE5861ACC03C009F6EC5397BE597162B7E83"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DuplicatePhotosFixer.UserControls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace DuplicatePhotosFixer.UserControls {
    
    
    /// <summary>
    /// ucResultObjectListView
    /// </summary>
    public partial class ucResultObjectListView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ObjectListView11;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblGroup;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblFileName;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblPath;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblSize;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblCreated;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblModified;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblFileType;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblImgWidth;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\UserControls\ucResultObjectListView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn lblImgHeight;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DuplicatePhotosFixer;component/usercontrols/ucresultobjectlistview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UserControls\ucResultObjectListView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ObjectListView11 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 2:
            this.lblGroup = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 3:
            this.lblFileName = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 4:
            this.lblPath = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 5:
            this.lblSize = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 6:
            this.lblCreated = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 7:
            this.lblModified = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 8:
            this.lblFileType = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 9:
            this.lblImgWidth = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 10:
            this.lblImgHeight = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

